### PR TITLE
Update useSessionStorage to support strings + add new options + add useReadSessionStorage

### PR DESCRIPTION
**Pull request by jonlinkens**
Fixes https://github.com/juliencrn/usehooks-ts/issues/335

Attempts to make `useSessionStorage` less opinionated in how session storage values are stored and parsed.

### Changes
- Add third `options` argument to `useSessionStorage`:
    - `parseAsJson: boolean` - default to true, pass as `false` when you don't want a value to be parsed using `JSON.parse`. This will fix the bug I was describing where a value has been previously set as a `string`
    - `parser: (value: string | null) => T` - a custom parser if you have stored a session storage value with a custom serializer function
    - `serializer: (value: T) => string` - a custom serializer to store values in a format different from the default behavior of `JSON.stringify`
- Renamed `initialValue` to `defaultValue` for readability
- Removed `undefined` value support - I can't imagine a case where this is needed over just not storing the key/value in session storage + removing this decreases complexity of the hook
    
- Add `useReadSessionStorage`, similar to `useReadLocalStorage`

### CODE REVIEW

**Comment by jonlinkens** [comment]
Going to close this as it seems this library is no longer maintained

**Comment by jonlinkens** [comment]
I think this can now be closed as addressed in https://github.com/juliencrn/usehooks-ts/pull/439?

**Comment by juliencrn** [comment]
> I think this can now be closed as addressed in #439? I'll leave open so you can confirm - Thank you very much btw!

Yes indeed! Thank you 👍 I will add you to the contributor list

**Comment by jonlinkens** [comment]
>  I, unfortunately, worked on it before seeing your one

No worries at all, just happy to see the bug fixed - thanks for your hard work on this library

**Comment by erichartline** [comment]
Any chance that we could still bring in the `useReadSessionStorage` hook from this PR? We have the equivalent for localStorage but not sessionStorage.

**Pull request closed without merging**
