### PR TITLE
fix: fixed up bug(#549) -Init use `useState` don't work in `useLocalStorage` 

### PR DESCRIPTION
**Pull request by LonelyFellas**
#549

### CODE REVIEW

**Comment by jraoult** [comment]
Thanks, @LonelyFellas, for trying to tackle that. That said, my gut feeling would be that the fix has to do with changing the `useLocalStorage.ts` file:

 https://github.com/juliencrn/usehooks-ts/blob/0f286bb13c28cb992c1c397ed1db22d4e72846b8/packages/usehooks-ts/src/useLocalStorage/useLocalStorage.ts#L122

to 
```ts
const setValue: Dispatch<SetStateAction<T>> = useCallback(value => {
```
With the appropriate dependency list rather than changing how `useEventCallback` behaves.

**Comment by jraoult** [comment]
@LonelyFellas, just a disclaimer: I'm not a repo maintainer, so my opinion is super relevant here.

My first point is that `useCallback` is the proper hook in this context instead of`useEventCallback`. My point is that `useEventCallback` from (or precedes) the now abandoned [`useEvent` RFC](https://github.com/reactjs/rfcs/blob/useevent/text/0000-useevent.md). It is explicitly built to stabilise the reference to a callback that is never run during a render phase. If a callback can/needs to be run in the render phase and we still want to stabilise the reference, we need to use `useCallback` instead (cf. [When useEvent should not be used?]( https://github.com/reactjs/rfcs/blob/useevent/text/0000-useevent.md#when-useevent-should-not-be-used)).

My second point would be that your proposed patch introduces a change in the contract of `useEventCallback`. Now `useEventCallback` return callback can be used in the render phase which it shouldn't  by design potentially breaking the code using it since the lack of dependency tracking. Here's a quote from the RFC:

> This makes it safe to preserve their identity despite the changing props/state inside. Because they can't be called during rendering, they can't affect the rendering output — and so they don't need to change when their inputs change (i.e. they're not "reactive").

But again, it would be up to @juliencrn to decide if my initial issue is something they think makes sense and then decide the proper way to implement it.

**Comment by juliencrn** [comment]
Thanks for the proposition, but we'll abandon this change. (https://github.com/juliencrn/usehooks-ts/issues/549#issuecomment-2024680380).

**Comment by juliencrn** [comment]
@all-contributors please add @jraoult for bug and review

**Comment by juliencrn** [comment]
@all-contributors please add @LonelyFellas for code

**Pull request closed without merging**
