### PR TITLE
Add support on useFetch

### PR DESCRIPTION
**Pull request by lit26**
- Add loading state
- Support for other types of response data
- Fix https://github.com/juliencrn/usehooks-ts/issues/266

### CODE REVIEW

**Comment by juliencrn** [comment]
Hi @lit26, 
Thanks for the PR but we'll depreciate this hook.

**Comment by tli26** [comment]
> Hi @lit26, 
> 
> Thanks for the PR but we'll depreciate this hook.

Why this is closed?

**Comment by juliencrn** [comment]
Because `useFetch` will be depreciated and dropped soon. 

I recommend you to use instead:
- your framework server-side stuff like RSC or getServerSideProps  for NextJS
- use the `use` hooks from react
- use `useQuery` or `useSWR` 

Our `useFetch` was a good example to learn how a react hook works, but it's an anti-pattern and not enterprise-grade.

**Comment by tli26** [comment]
I see. Thanks

**Pull request closed without merging**
