### PR TITLE
fix: useScript failed to remove script from cache when passing `removeOnUnmount` prop

### PR DESCRIPTION
**Pull request by ShanSenanayake**
The `removeOnUnmount` prop didn't remove the script from the cache. This created a side effect where if you try and render the same component by mounting -> unmounting -> mounting again, the `useScript` hook behaves as the script is loaded when in reality is has remove the script from the tree but failed to remove it from the cache.

Issue: https://github.com/juliencrn/usehooks-ts/issues/314

### CODE REVIEW

**Comment by scottwiw** [comment]
Any bump on this? Ran into this issue while trying to add a Hubspot calendar iframe and this definitely fixes it.

**Comment by ShanSenanayake** [comment]
@scottwiw based on [this issue](https://github.com/juliencrn/usehooks-ts/issues/373), and the amount of PRs that has no activity I think this package is basically abandoned, I would suggest co locating the whole `useScript` and fixing it yourself.

**Comment by scottwiw** [comment]
> @scottwiw based on [this issue](https://github.com/juliencrn/usehooks-ts/issues/373), and the amount of PRs that has no activity I think this package is basically abandoned, I would suggest co locating the whole `useScript` and fixing it yourself.

Thanks, I'll make do. Appreciate it!

**Comment by juliencrn** [comment]
Thank you @ShanSenanayake 👍

**Pull request merged**
