### PR TITLE
Add Map & Set to useLocalStorage control

### PR DESCRIPTION
**Pull request by AlecsFarias**
-> enable useLocalStorage hook to work with Map and Set 
-> check instance types of `initialValue` to work with return type on `readValue`
-> create `stringify` function to work separately with type checking and string build

issue: #308

### CODE REVIEW

**Comment by DevBrasil** [comment]
Hi, very usefull function

**Comment by DevBrasil** [comment]
Hi, very usefull function

**Comment by alexandreferris** [comment]
finally someone did it 🙌🏻

**Comment by juliencrn** [comment]
Hi you all, good feature indeed. As the PR's base branch is outdated, I moved this code there #439.
It should be in the next release
Thanks!

**Pull request closed without merging**
